config/routes.rb
Rails.application.routes.draw do
  resources :fake_professionals
  root to: "home#index"
  devise_for :users
  resources :sizes
  resources :animals
  resources :items
  resources :categories
  
  get "/get_professionals", to: "fake_professionals#json_url"
  get "/get_categories", to: "categories#json_url"
  get "/get_animals", to: "animals#json_url"
  get "/get_items", to: "items#json_url"
  get "/get_sizes", to: "sizes#json_url"
  get "/get_users", to: "user_own#json_url"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  before_action :set_size, only: [:show, :edit, :update, :destroy]

  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
    @SizeItem = SizeItem.where("size_id = ?", params[:id])
  end

  def json_url
    render json: Size.all
  end

  # GET /sizes/new
  def new
    @size = Size.new
  end

  # GET /sizes/1/edit
  def edit
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(size_params)

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render :show, status: :created, location: @size }
      else
        format.html { render :new }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sizes/1
  # PATCH/PUT /sizes/1.json
  def update
    respond_to do |format|
      if @size.update(size_params)
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { render :show, status: :ok, location: @size }
      else
        format.html { render :edit }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size.destroy
    respond_to do |format|
      format.html { redirect_to sizes_url, notice: 'Size was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_size
      @size = Size.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def size_params
      params.require(:size).permit(:title, :color)
    end
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/sizes/edit.html.erb
<% if current_user && current_user.admin %>
    <div class="container">
        <h1>Editing Size</h1>

        <%= render 'form', size: @size %>
    </div>
<%end%>

app/views/sizes/index.html.erb
<% if current_user && current_user.admin %>  
  <div class="container">
    <h1>Sizes</h1>
    <% @sizes.each do |size| %>
      <div class="margin-top">
        <div class="card">
          <div class="margin-top">  
            <span class="badge badge-pill text-uppercase" style="background-color: <%= size.color %>">
              <%= link_to size.title, size, class:"text-white"%>
            </span>
          </div>
          <p class="text-secondary"><%= size.created_at %></p>
          <div>
            <%= link_to 'Show', size, :class => "btn btn-info btn-lg" %>
            <%= link_to 'Edit', edit_size_path(size), :class => "btn btn-secondary btn-lg" %>
            <%= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-lg" %>
          </div>     
        </div>  
      </div>
    <% end %>
    <br>
    <%= link_to 'New Size', new_size_path, :class => "btn btn-primary" %>
  </div>
<%end%>

app/views/sizes/new.html.erb
<% if current_user && current_user.admin %>
    <div class="container">
        <h1>New Size</h1>

        <%= render 'form', size: @size %>
    </div>
<%end%>

app/views/sizes/show.html.erb
<% if current_user && current_user.admin %>  
  <div class="container">
    <div class="margin-top">
      <h1 style="color:<%= @size.color %>">Items from <%= @size.title %></h1>
    </div>
    <% @SizeItem.each do |sizeItem| %>
      <div class="margin-top">
        <div class="card"> 
            <h1 class="text-uppercase"><%= Item.find(sizeItem.item_id).name %></h1>
            <p><strong>Description:</strong> <%= Item.find(sizeItem.item_id).description %></p>
            <p><strong>Price:</strong> <%= Item.find(sizeItem.item_id).price %>$</p>
            <p><strong>Stock:</strong> <%= Item.find(sizeItem.item_id).stock %></p>
          <div>
            <% if current_user && current_user.admin%>
              <%= link_to 'Edit', edit_item_path(sizeItem.item_id), :class=> "btn btn-success btn-lg" %> 
            <% end %>
            <%= link_to 'Show', item_path(sizeItem.item_id), :class=> "btn btn-primary btn-lg" %>
            <%= link_to 'Back', sizes_path, :class=> "btn btn-secondary btn-lg" %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
<%end%>