config/routes.rb
Rails.application.routes.draw do
  resources :fake_professionals
  root to: "home#index"
  devise_for :users
  resources :sizes
  resources :animals
  resources :items
  resources :categories
  
  get "/get_professionals", to: "fake_professionals#json_url"
  get "/get_categories", to: "categories#json_url"
  get "/get_animals", to: "animals#json_url"
  get "/get_items", to: "items#json_url"
  get "/get_sizes", to: "sizes#json_url"
  get "/get_users", to: "user_own#json_url"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :animal_items
    has_many :items, through: :animal_items
    has_one_attached :banner

    validates :title, presence: true, length: { in: 3..12 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters"}, uniqueness: true
    validates :color, presence: true, exclusion: { in: %w(FFFFFF ffffff), message: "white it's disable" }
    validates :banner, presence: true #format:  { with: /\A.+[.][png|jpg]\z/}

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @AnimalItem = AnimalItem.where("animal_id = ?", params[:id])
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  def json_url
    @animal = Animal.all.with_attached_banner
    render json: @animal.map { |animal|
      animal.as_json.merge({ banner: url_for(animal.banner) })
    }
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.banner.destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:title, :color, :banner)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :banner %>
  </div>
  

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-lg btn-block" %>
    <%= link_to 'Cancel', animals_path, :class => "btn btn-secondary btn-lg btn-block" %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<% if current_user && current_user.admin %>    
    <div class="container">
        <h1>Editing Animal</h1>

        <%= render 'form', animal: @animal %>
    </div>
<%end%>

app/views/animals/new.html.erb
<% if current_user && current_user.admin %>
    <div class="container">
        <h1>New Animal</h1>

        <%= render 'form', animal: @animal %>
    </div>
<%end%>

app/views/animals/show.html.erb
<% if current_user && current_user.admin %>
  <div class="container">
    <div class="margin-top">
      <h1 style="color:<%= @animal.color %>">Items from <%= @animal.title %></h1>
    </div>
    <% @AnimalItem.each do |animalItem| %>
      <div class="margin-top">
        <div class="card"> 
            <h1 class="text-uppercase"><%= Item.find(animalItem.item_id).name %></h1>
            <p><strong>Description:</strong> <%= Item.find(animalItem.item_id).description %></p>
            <p><strong>Price:</strong> <%= Item.find(animalItem.item_id).price %>$</p>
            <p><strong>Stock:</strong> <%= Item.find(animalItem.item_id).stock %></p>
          <div>
            <% if current_user && current_user.admin%>
              <%= link_to 'Edit', edit_item_path(animalItem.item_id), :class=> "btn btn-success btn-lg" %> 
            <% end %>
            <%= link_to 'Show', item_path(animalItem.item_id), :class=> "btn btn-primary btn-lg" %>
            <%= link_to 'Back', animals_path, :class=> "btn btn-secondary btn-lg" %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
<%end%>