config/routes.rb
Rails.application.routes.draw do
  resources :fake_professionals
  root to: "home#index"
  devise_for :users
  resources :sizes
  resources :animals
  resources :items
  resources :categories
  
  get "/get_professionals", to: "fake_professionals#json_url"
  get "/get_categories", to: "categories#json_url"
  get "/get_animals", to: "animals#json_url"
  get "/get_items", to: "items#json_url"
  get "/get_sizes", to: "sizes#json_url"
  get "/get_users", to: "user_own#json_url"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :category_items
    has_many :items, through: :category_items
    validates :title, presence: true, length: { in: 3..20 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters"}, uniqueness: true
    validates :color, presence: true, exclusion: { in: %w(FFFFFF ffffff), message: "white it's disable" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @CategoryItem = CategoryItem.where("category_id = ?", params[:id])
  end

  def json_url
    render json: Category.all
  end
  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% if current_user && current_user.admin %>
    <div class="container">
        <h1>Editing Category</h1>

        <%= render 'form', category: @category %>
    </div>
<%end%>

app/views/categories/index.html.erb
<% if current_user && current_user.admin %>
  <div class="container">
    <h1>Categories</h1>
    <% @categories.each do |category| %>
      <div class="margin-top">
        <div class="card">
          <div class="margin-top">  
            <span class="badge badge-pill text-uppercase" style="background-color: <%= category.color %>">
              <%= link_to category.title, category, class:"text-white"%>
            </span>
          </div>
          <p class="text-secondary"><%= category.created_at %></p>
          <div>
            <%= link_to 'Show', category, :class => "btn btn-info btn-lg" %>
            <%= link_to 'Edit', edit_category_path(category), :class => "btn btn-secondary btn-lg" %>
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-lg" %>
          </div>     
        </div>  
      </div>
    <% end %>
    <br>
    <%= link_to 'New Category', new_category_path, :class => "btn btn-primary" %>
  </div>
<%end%>

app/views/categories/new.html.erb
<% if current_user && current_user.admin %>
    <div class="container">
        <h1>New Category</h1>

        <%= render 'form', category: @category %>
    </div>
<%end%>

app/views/categories/show.html.erb
<% if current_user && current_user.admin %>
  <div class="container">
    <div class="margin-top">
      <h1 style="color:<%= @category.color %>">Items from <%= @category.title %></h1>
    </div>
    <% @CategoryItem.each do |categoryItem| %>
      <div class="margin-top">
        <div class="card"> 
            <h1 class="text-uppercase"><%= Item.find(categoryItem.item_id).name %></h1>
            <p><strong>Description:</strong> <%= Item.find(categoryItem.item_id).description %></p>
            <p><strong>Price:</strong> <%= Item.find(categoryItem.item_id).price %>$</p>
            <p><strong>Stock:</strong> <%= Item.find(categoryItem.item_id).stock %></p>
          <div>
            <% if current_user && current_user.admin%>
              <%= link_to 'Edit', edit_item_path(categoryItem.item_id), :class=> "btn btn-success btn-lg" %> 
            <% end %>
            <%= link_to 'Show', item_path(categoryItem.item_id), :class=> "btn btn-primary btn-lg" %>
            <%= link_to 'Back', categories_path, :class=> "btn btn-secondary btn-lg" %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
<%end%>