config/routes.rb
Rails.application.routes.draw do
  resources :fake_professionals
  root to: "home#index"
  devise_for :users
  resources :sizes
  resources :animals
  resources :items
  resources :categories
  
  get "/get_professionals", to: "fake_professionals#json_url"
  get "/get_categories", to: "categories#json_url"
  get "/get_animals", to: "animals#json_url"
  get "/get_items", to: "items#json_url"
  get "/get_sizes", to: "sizes#json_url"
  get "/get_users", to: "user_own#json_url"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="w3-row-padding w3-padding-32 w3-serif">
  <div class="w3-third">
  <h1>About Us</h1>
    <p>Double D Pet Shop is the leading chain of pet shops in Spain.
    At Double D Pet Shop we are specialists in all types of animals and we have
    a team of over 1,000 people dedicated to helping improve the lives of all pets,
    so an animal lover is not just a customer, is a friend.
    To help you take care of and enjoy your best friend, we have the best offers in the sector and the most specialized staff.</p>
  </div>

	<div class="w3-third w3-serif">
    <h1>Conctact Us</h1>
    <ul class="w3-ul w3-hoverable">
      <li class="w3-padding-16">
        <span>Phone Number: 928 XX XX XX</span><br>
      </li>
      <li class="w3-padding-16">
        <span>Email: DoubleD@admin.com</span><br>
      </li>
      <li class="w3-padding-16">
        <span>Address: C/ calle</span><br>
      </li> 
    </ul>
  </div>

  <div class="w3-third w3-serif">
    <h1>Social Medias</h1>
    <ul class="w3-ul w3-hoverable">
      <li class="w3-padding-16">
        <img src="/images/twitter.png" class="w3-left w3-margin-right">
        <span class="w3-large">Twitter</span><br>
        <span>@DoubleDPS</span>
      </li>
      <li class="w3-padding-16">
        <img src="/images/insta.png" class="w3-left w3-margin-right">
        <span class="w3-large">Instagram</span><br>
        <span>@DoubleDPS</span>
      </li> 
      <li class="w3-padding-16">
        <img src="/images/facebook.png" class="w3-left w3-margin-right">
        <span class="w3-large">Facebook</span><br>
        <span>DoubleDPS</span>
      </li> 
    </ul>
  </div>
</footer>

app/views/layouts/_navs.html.erb
<div class="topnav" id="myTopnav">
    <%= link_to "DoubleD", root_path, class:"active"%>
  
    <%if current_user %>
        <% if current_user.admin %>

                <%= link_to "Add Animal", new_animal_path, class:"nav-link"%>
            
            
                <%= link_to "Add Category", new_category_path, class:"nav-link"%>
           
            
                <%= link_to "Add Size", new_size_path, class:"nav-link"%>
            
            
                <%= link_to "Add Item", new_item_path, class:"nav-link"%>

                <%= link_to "Add Professional", new_fake_professional_path, class:"nav-link"%>
    
        <%end%>
        
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        
    <%else%>
        
            <%= link_to "Sign up", new_user_registration_path, class:"nav-link"%>
        
        
            <%= link_to "Sign in", user_session_path, class:"nav-link"%>
        
    <%end%>
  
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>


<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>


<% if notice %>
    <p class="notice alert-primary"><%= notice %></p>
<%end%>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetshopApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script 
      src="https://code.jquery.com/jquery-3.1.1.slim.min.js" 
      integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" 
      crossorigin="anonymous">
    </script> 
    <script src="app/javascript/nav-utils.js"></script>
  </head>

  <body>
    <%= render "layouts/navs" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>